<%@ Page Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="BoardList.aspx.cs" Inherits="JKParkLaw.Admin.Board.BoardList" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<%@ Register Assembly="FredCK.FCKeditorV2" Namespace="FredCK.FCKeditorV2" TagPrefix="FCKeditorV2" %>
<%@ Register TagPrefix="uc" TagName="upload" Src="~/Admin/Controls/Common/img_uploader.ascx" %>

<%@ MasterType VirtualPath="~/Admin/Admin.Master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AdminPlaceHolder" runat="server">
<div class="row">
        <asp:ScriptManager ID="ScriptManager2" runat="server">
        </asp:ScriptManager>

        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
        
            <table class="table">
                <tr>
                    <td style="width:250px;"><b>Category:</b></td>
                    <td>
                        <asp:DropDownList ID="ddlBoardCatID_Sort" runat="server" DataSourceID="DS_BoardCategory" DataTextField="BoardCategory" DataValueField="BoardCatID" CssClass="form-control" AutoPostBack="true" OnSelectedIndexChanged="RefreshList"></asp:DropDownList>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"> 
                        <asp:GridView ID="gridList" runat="server" AutoGenerateColumns="False"  AllowPaging="true" PageSize="15"
                            Width="100%"  DataKeyNames="UID" OnPageIndexChanging="gridList_PageIndexChanging"
                            AllowSorting="True" CssClass= "table table-striped table-bordered" AutoGenerateDeleteButton="true"  
                            OnRowDeleting="gridList_RowDeleting" OnRowDeleted="gridList_RowDeleted">
                            <Columns>
                                <asp:BoundField DataField="UID" HeaderText="ID" InsertVisible="False" 
                                    ReadOnly="True" />
                                <asp:BoundField DataField="OrderNoDisplay" HeaderText="Display Order" InsertVisible="False"  ItemStyle-HorizontalAlign="Center"
                                    ReadOnly="True"  />
                                <asp:BoundField DataField="BoardCategory" HeaderText="Category"  />
                                <asp:BoundField DataField="BoardTitle" HeaderText="Title"  />
                                <asp:BoundField DataField="ControlDate" HeaderText="Date"  DataFormatString="{0:MM/dd/yyyy}"/>
                                <asp:TemplateField HeaderText="Edit" ItemStyle-HorizontalAlign="Center"   >
                                <ItemTemplate>
                                    <asp:HyperLink ID="BoardHL" runat="server" CssClass="normalLinks"
                                        NavigateUrl='<%# Eval("UID", "Board.aspx?id={0}") %>' Text="Edit"></asp:HyperLink>
                                </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>
                         <asp:SqlDataSource ID="DS_Main" runat="server" CancelSelectOnNullParameter="false"
                            ConnectionString="<%$ ConnectionStrings:SiteDBConnection %>" SelectCommand="up_board_retrieve" SelectCommandType="StoredProcedure" 
                            InsertCommand="up_board_insert" InsertCommandType="StoredProcedure"
                            DeleteCommand="up_board_delete" DeleteCommandType="StoredProcedure"
                            >
                            <SelectParameters>
                                <asp:ControlParameter ControlID="ddlBoardCatID_Sort" PropertyName="SelectedValue" Name="BoardCatID" Type="Int32" DefaultValue="0" />
                            </SelectParameters>
                            <InsertParameters>
                                <asp:ControlParameter ControlID="ModifiedDate" PropertyName="Text" Name="ControlDate" Type="DateTime" />
                                <asp:ControlParameter ControlID="tbBoardTitle" PropertyName="Text" Name="BoardTitle" Type="String" />
                                <asp:ControlParameter ControlID="txtBoardContent" PropertyName="Value" Name="BoardContent" Type="String" />
                                <asp:ControlParameter ControlID="txtBOrder" PropertyName="Text" Name="BOrder" Type="Int32"/>
                                <asp:ControlParameter ControlID="ddlBoardCatID" PropertyName="SelectedValue" Name="BoardCatID" Type="Int32"/>
                            </InsertParameters>
                            <DeleteParameters>
                                <asp:Parameter Name="UID" Type="Int64" DefaultValue="0" ConvertEmptyStringToNull="true" />
                            </DeleteParameters>
                        </asp:SqlDataSource>    
                   </td>
                </tr>
        
                <tr>
                    <td colspan="2" class="head"><strong>Add Message
                    </td>
                </tr>
                <tr>
                    <td style="width:250px;"> Category<span class="error">*</span></td>
                    <td>
                        <asp:DropDownList ID="ddlBoardCatID" runat="server" DataSourceID="DS_BoardCategory_Detail" DataTextField="BoardCategory" DataValueField="BoardCatID" CssClass="form-control multiselect"></asp:DropDownList>
                        <asp:RequiredFieldValidator ID="rfv_ddlBoardCatID" runat="server" ControlToValidate="ddlBoardCatID" InitialValue="0" ErrorMessage="* required field" Display="Dynamic" SetFocusOnError="true" ValidationGroup="AddNew"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td> Title<span class="error">*</span></td>
                    <td>
                        <asp:TextBox  ID="tbBoardTitle" runat="server" MaxLength="125"  CssClass="form-control">  </asp:TextBox>
                    </td>
                </tr>
        
                <tr class="alternate1">
                    <td >Description<span class="error">*</span></td>
                    <td>
                        <FCKeditorV2:FCKeditor Width="800" Height="300" ToolbarSet="EShop" ID="txtBoardContent" runat="server" BasePath="~/Images/js/fckeditor/" AutoDetectLanguage="True"></FCKeditorV2:FCKeditor>
                        <br />
                        Insert Image to Content:&nbsp;
                        <uc:upload id="upload1" runat="server" image_upload_folder="/Files/images/board/" max_size="2048"></uc:upload>
                        <asp:Label ID="lblMsgUpload1" runat="server" ForeColor="Red"></asp:Label>
                        <br />
                    </td>
                </tr>
                <tr>
                    <td class="head"><b>Display Order:</b>&nbsp;
                    <td>
                        <asp:TextBox id="txtBOrder" runat="server" MaxLength="10" CssClass="form-control"></asp:TextBox>
                        <asp:CompareValidator id="CompareValidator1" runat="server" ControlToValidate="txtBOrder" Operator="DataTypeCheck" 
                            Type="Integer"  Display="Dynamic" ErrorMessage="Value should be numeric."  ValidationGroup="AddNew"/>
                        <asp:CompareValidator id="CompareValidator2" runat="server" ControlToValidate="txtBOrder" Operator="GreaterThanEqual" ValueToCompare="0"
                            Type="Integer"  Display="Dynamic" ErrorMessage="Value should be a positive number."  ValidationGroup="AddNew"/>
                    </td>
                </tr>
           
                <tr>
                    <td >Date<span class="error">*</span></td>
                    <td >
                    <asp:TextBox ID="ModifiedDate" runat="server" />
                        <ajaxToolkit:CalendarExtender ID="ModifiedCalExtender" runat="server" TargetControlID="ModifiedDate" PopupButtonID="ModImgUrl" Format="MM/dd/yyyy" />
                        <asp:ImageButton ID="ModImgUrl" runat="server" 
                            ImageUrl="~/Images/icons/calendar.gif" />
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="ModifiedDate" ValidationGroup="AddNew">*</asp:RequiredFieldValidator>                    
                    (MM/dd/yyyy)</td>
                </tr>
                <tr>
                     <td>
                        * Required fields
                    </td>
                    <td>
                        <asp:Label ID="lblMessage" ForeColor="Red" runat="server" Text=""></asp:Label>
                    </td>
                </tr>
         
                <tr>
                    <td colspan="2">
                        <asp:Button ID="btAdd" runat="server" Text="Add Message"  ValidationGroup="AddNew" OnClick="btAdd_Click" CssClass="btn btn-primary" />
                    </colspan="">
                </tr>
            </table>
        </ContentTemplate>
        <Triggers>
            <asp:PostBackTrigger ControlID="upload1" />
        </Triggers>
    </asp:UpdatePanel>
</div>

    <asp:SqlDataSource ID="DS_BoardCategory" runat="server" CancelSelectOnNullParameter="false"
        ConnectionString="<%$ ConnectionStrings:SiteDBConnection %>" SelectCommand="up_boardcategories_retrieveforlistitem" SelectCommandType="StoredProcedure" 
        >
        <SelectParameters>
            <asp:Parameter Name="List" Type="String" DefaultValue="1" />
        </SelectParameters>
    </asp:SqlDataSource>
    
    <asp:SqlDataSource ID="DS_BoardCategory_Detail" runat="server" CancelSelectOnNullParameter="false"
        ConnectionString="<%$ ConnectionStrings:SiteDBConnection %>" SelectCommand="up_boardcategories_retrieveforlistitem" SelectCommandType="StoredProcedure" 
        >
        <SelectParameters>
        </SelectParameters>
    </asp:SqlDataSource>
</asp:Content>
