<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" 
CodeBehind="OtherList.aspx.cs" Inherits="JKParkLaw.Admin.Other.OtherList" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<%@ Register Assembly="FredCK.FCKeditorV2" Namespace="FredCK.FCKeditorV2" TagPrefix="FCKeditorV2" %>
<%@ Register TagPrefix="uc" TagName="upload" Src="~/Admin/Controls/Common/img_uploader.ascx" %>

<%@ MasterType VirtualPath="~/Admin/Admin.Master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AdminPlaceHolder" runat="server">
    <div class="row">
        <asp:ScriptManager ID="ScriptManager2" runat="server">
        </asp:ScriptManager>

        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
        
        <table class="table">
            <tr>
                <td colspan="2"> 
                    <asp:GridView ID="OthersGrid" runat="server" AutoGenerateColumns="False"  AllowPaging="true" PageSize="15"
                        Width="100%"  DataKeyNames="ID" OnPageIndexChanging="OthersGrid_PageIndexChanging"
                        AllowSorting="True" CssClass= "table table-striped table-bordered" AutoGenerateDeleteButton="true" 
                        OnRowDeleting="OthersGrid_RowDeleting" OnRowDeleted="OthersGrid_RowDeleted">
                        <Columns>
                            <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" 
                                ReadOnly="True"  />
                            <asp:BoundField DataField="RowNumber" HeaderText="No" InsertVisible="False" 
                                ReadOnly="True"  />
                            <asp:BoundField DataField="Title" HeaderText="Title" />
                            <asp:BoundField DataField="Modified" HeaderText="Mod Date" ItemStyle-Width="100px" 
                                DataFormatString="{0:MM/dd/yyyy}"/>
                            <asp:CheckBoxField DataField="Hidden" HeaderText="Hidden"  />
                            <asp:TemplateField HeaderText="Edit" ItemStyle-HorizontalAlign="Center">
                            <ItemTemplate>
                                <asp:HyperLink ID="NewsHL" runat="server" CssClass="normalLinks"
                                    NavigateUrl='<%# Eval("ID", "Other.aspx?ID={0}") %>' Text="Edit"></asp:HyperLink>
                            </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                     <asp:SqlDataSource ID="NewsViewSource" runat="server" 
                        ConnectionString="<%$ ConnectionStrings:SiteDBConnection %>" SelectCommand="SELECT * FROM [Others]" SelectCommandType="Text" >
                    </asp:SqlDataSource>    
               </td>
            </tr>
      
            <tr>
                <td colspan="2" class="head"><strong>Add New Item 
                </td>
            </tr>
            <tr>
                <td  style="width:250px;"> Title<span class="error">*</span></td>
                <td>
                    <asp:TextBox  ID="tbTitle" runat="server" MaxLength="255"  CssClass="form-control">  </asp:TextBox>
                </td>
            </tr>
            <tr>
                <td> Source</td>
                <td>
                    <asp:TextBox  ID="tbSource" runat="server" MaxLength="125"  CssClass="form-control">  </asp:TextBox>
                </td>
            </tr>
            <tr>
                <td> Author</td>
                <td>
                    <asp:TextBox  ID="tbAuthor" runat="server" MaxLength="50" CssClass="form-control">  </asp:TextBox>
                </td>
            </tr>
            <tr style="display:none;">
                <td>Small desc</td>
                <td><textarea id="SmallDesc" cols="60" rows="3" runat="server" class="form-control"></textarea></td>
            </tr>
            <tr class="alternate1">
                <td >Description<span class="error">*</span></td>
                <td>
                    <FCKeditorV2:FCKeditor Width="800" Height="300" ToolbarSet="EShop" ID="BigDesc" runat="server" BasePath="~/Images/js/fckeditor/" AutoDetectLanguage="True"></FCKeditorV2:FCKeditor>
                    <br />
                    Insert Image to Content:&nbsp;
                    <uc:upload id="upload1" runat="server" image_upload_folder="/Files/images/other/" max_size="2048"></uc:upload>
                    <asp:Label ID="lblMsgUpload1" runat="server" ForeColor="Red"></asp:Label>
                    <br />
                </td>
            </tr>
            <tr>
                <td>
                    Hidden</td>
                <td>
                    <asp:CheckBox ID="cbHidden" runat="server" />
                </td>
             </tr>
            <tr>
                <td >Modified<span class="error">*</span></td>
                <td >
                <asp:TextBox ID="ModifiedDate" runat="server"  />
                    <ajaxToolkit:CalendarExtender ID="ModifiedCalExtender" runat="server" TargetControlID="ModifiedDate" PopupButtonID="ModImgUrl" Format="MM/dd/yyyy" />
                    <asp:ImageButton ID="ModImgUrl" runat="server" 
                        ImageUrl="~/Images/icons/calendar.gif" />
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="ModifiedDate" ValidationGroup="AddNew">*</asp:RequiredFieldValidator>                    
                (MM/dd/yyyy)</td>
            </tr>
            <tr>
                <td>* Required fields</td>
                <td >
                    <asp:Label ID="lblMessage" ForeColor="Red" runat="server" Text=""></asp:Label>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:Button ID="AddNewOther" runat="server" Text="Add Item"  ValidationGroup="AddNew" OnClick="AddNewContent_Click" CssClass="btn btn-primary" />
                </td>
            </tr>
        </table>
        </ContentTemplate>
        <Triggers>
            <asp:PostBackTrigger ControlID="upload1" />
        </Triggers>
        </asp:UpdatePanel>
    </div>
</asp:Content>
